### PR TITLE
Add Glo Dollar 

### PR DESCRIPTION
**Pull request by Jesse-Sawa**

### CODE REVIEW

**Comment by gglucass** [comment]
@Jesse-Sawa thanks so much for getting this done so quickly! I was wondering if you could replace the icon with this one though? https://i.imgur.com/k5ug2KE.png

That one should render a little nicer on Uniswap :-)

**Comment by arthurgousset** [comment]
> @Jesse-Sawa thanks so much for getting this done so quickly! I was wondering if you could replace the icon with this one though? https://i.imgur.com/k5ug2KE.png
> 
> That one should render a little nicer on Uniswap :-)

Just saw your comment by coincidence. Is this is still relevant @gglucass ? 
Feel free to open a PR to change the icon if you'd like.

**Comment by gglucass** [comment]
> > @Jesse-Sawa thanks so much for getting this done so quickly! I was wondering if you could replace the icon with this one though? https://i.imgur.com/k5ug2KE.png
> > That one should render a little nicer on Uniswap :-)
> 
> Just saw your comment by coincidence. Is this is still relevant @gglucass ? Feel free to open a PR to change the icon if you'd like.

Thanks for the note @arthurgousset - this has already been resolved, the repo now points to our own hosted logo on https://app.glodollar.org/glo-logo.svg

**Comment by arthurgousset** [comment]
Nice, glad this is resolved!

**Pull request merged**
